version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: 123456
  pgadm:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 8081:80
    links:
      - "db:database"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
  microservice:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - "db:database"
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}