version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: 123456
  pgadm:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 8081:80
    links:
      - "db:database"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    links:
      - "zookeeper:zookeeper"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://127.0.0.1:9092,EXTERNAL://kafka:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
  Kowl:
    image: quay.io/cloudhut/kowl:master
    restart: on-failure
    ports:
      - '8082:8080'
    links:
      - "kafka:kafka"
    environment:
      KAFKA_BROKERS: kafka:9093
    depends_on:
      - kafka
  microservice:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - "db:database"
      - "kafka:kafka"
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BASE_URL: ${KAFKA_BASE_URL}
    depends_on:
      - kafka